#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/config/local_llm_stack/local_harness.env"
CALLER_LOCAL_QWEN_MODEL="${LOCAL_QWEN_MODEL+x}${LOCAL_QWEN_MODEL-}"
CALLER_CODEX_TEXTGEN_TARGET_BASE="${CODEX_TEXTGEN_TARGET_BASE+x}${CODEX_TEXTGEN_TARGET_BASE-}"
CALLER_CODEX_TEXTGEN_CONTEXT_LIMIT_TOKENS="${CODEX_TEXTGEN_CONTEXT_LIMIT_TOKENS+x}${CODEX_TEXTGEN_CONTEXT_LIMIT_TOKENS-}"
CALLER_CODEX_TEXTGEN_MAX_OUTPUT_TOKENS="${CODEX_TEXTGEN_MAX_OUTPUT_TOKENS+x}${CODEX_TEXTGEN_MAX_OUTPUT_TOKENS-}"
CALLER_CODEX_TEXTGEN_TOOL_TEMPERATURE="${CODEX_TEXTGEN_TOOL_TEMPERATURE+x}${CODEX_TEXTGEN_TOOL_TEMPERATURE-}"
CALLER_CODEX_TEXTGEN_TOOL_TOP_P="${CODEX_TEXTGEN_TOOL_TOP_P+x}${CODEX_TEXTGEN_TOOL_TOP_P-}"
CALLER_CODEX_TEXTGEN_TOOL_TOP_K="${CODEX_TEXTGEN_TOOL_TOP_K+x}${CODEX_TEXTGEN_TOOL_TOP_K-}"
CALLER_CODEX_TEXTGEN_TOOL_MIN_P="${CODEX_TEXTGEN_TOOL_MIN_P+x}${CODEX_TEXTGEN_TOOL_MIN_P-}"
CALLER_CODEX_TEXTGEN_TOOL_REASONING_EFFORT="${CODEX_TEXTGEN_TOOL_REASONING_EFFORT+x}${CODEX_TEXTGEN_TOOL_REASONING_EFFORT-}"
CALLER_CODEX_TEXTGEN_ENABLE_THINKING="${CODEX_TEXTGEN_ENABLE_THINKING+x}${CODEX_TEXTGEN_ENABLE_THINKING-}"
CALLER_CODEX_TEXTGEN_PRESERVE_THINKING="${CODEX_TEXTGEN_PRESERVE_THINKING+x}${CODEX_TEXTGEN_PRESERVE_THINKING-}"
CALLER_CODEX_TEXTGEN_THINKING_MIN_OUTPUT_TOKENS="${CODEX_TEXTGEN_THINKING_MIN_OUTPUT_TOKENS+x}${CODEX_TEXTGEN_THINKING_MIN_OUTPUT_TOKENS-}"
CALLER_CODEX_TEXTGEN_DISABLE_THINKING_FOR_TOOLS="${CODEX_TEXTGEN_DISABLE_THINKING_FOR_TOOLS+x}${CODEX_TEXTGEN_DISABLE_THINKING_FOR_TOOLS-}"
CALLER_CODEX_TEXTGEN_REASONING_DEFAULT_EFFORT="${CODEX_TEXTGEN_REASONING_DEFAULT_EFFORT+x}${CODEX_TEXTGEN_REASONING_DEFAULT_EFFORT-}"
CALLER_CODEX_TEXTGEN_REASONING_BUDGET_LOW="${CODEX_TEXTGEN_REASONING_BUDGET_LOW+x}${CODEX_TEXTGEN_REASONING_BUDGET_LOW-}"
CALLER_CODEX_TEXTGEN_REASONING_BUDGET_MEDIUM="${CODEX_TEXTGEN_REASONING_BUDGET_MEDIUM+x}${CODEX_TEXTGEN_REASONING_BUDGET_MEDIUM-}"
CALLER_CODEX_TEXTGEN_REASONING_BUDGET_XHIGH="${CODEX_TEXTGEN_REASONING_BUDGET_XHIGH+x}${CODEX_TEXTGEN_REASONING_BUDGET_XHIGH-}"
CALLER_CODEX_TEXTGEN_REASONING_OUTPUT_RESERVE_TOKENS="${CODEX_TEXTGEN_REASONING_OUTPUT_RESERVE_TOKENS+x}${CODEX_TEXTGEN_REASONING_OUTPUT_RESERVE_TOKENS-}"
CALLER_CODEX_TEXTGEN_NATIVE_TOOLS="${CODEX_TEXTGEN_NATIVE_TOOLS+x}${CODEX_TEXTGEN_NATIVE_TOOLS-}"
CALLER_CODEX_TEXTGEN_SYSTEM_PROMPT_FILE="${CODEX_TEXTGEN_SYSTEM_PROMPT_FILE+x}${CODEX_TEXTGEN_SYSTEM_PROMPT_FILE-}"
CALLER_CODEX_TEXTGEN_LOG_PATH="${CODEX_TEXTGEN_LOG_PATH+x}${CODEX_TEXTGEN_LOG_PATH-}"
CALLER_LOCAL_QWEN_GUARD_PROFILE="${LOCAL_QWEN_GUARD_PROFILE+x}${LOCAL_QWEN_GUARD_PROFILE-}"
CALLER_LOCAL_QWEN_CODEX_MAX_TOOL_CALLS="${LOCAL_QWEN_CODEX_MAX_TOOL_CALLS+x}${LOCAL_QWEN_CODEX_MAX_TOOL_CALLS-}"
CALLER_LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS="${LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS+x}${LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS-}"
if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi
[[ "$CALLER_LOCAL_QWEN_MODEL" == x* ]] && LOCAL_QWEN_MODEL="${CALLER_LOCAL_QWEN_MODEL#x}"
[[ "$CALLER_CODEX_TEXTGEN_TARGET_BASE" == x* ]] && CODEX_TEXTGEN_TARGET_BASE="${CALLER_CODEX_TEXTGEN_TARGET_BASE#x}"
[[ "$CALLER_CODEX_TEXTGEN_CONTEXT_LIMIT_TOKENS" == x* ]] && CODEX_TEXTGEN_CONTEXT_LIMIT_TOKENS="${CALLER_CODEX_TEXTGEN_CONTEXT_LIMIT_TOKENS#x}"
[[ "$CALLER_CODEX_TEXTGEN_MAX_OUTPUT_TOKENS" == x* ]] && CODEX_TEXTGEN_MAX_OUTPUT_TOKENS="${CALLER_CODEX_TEXTGEN_MAX_OUTPUT_TOKENS#x}"
[[ "$CALLER_CODEX_TEXTGEN_TOOL_TEMPERATURE" == x* ]] && CODEX_TEXTGEN_TOOL_TEMPERATURE="${CALLER_CODEX_TEXTGEN_TOOL_TEMPERATURE#x}"
[[ "$CALLER_CODEX_TEXTGEN_TOOL_TOP_P" == x* ]] && CODEX_TEXTGEN_TOOL_TOP_P="${CALLER_CODEX_TEXTGEN_TOOL_TOP_P#x}"
[[ "$CALLER_CODEX_TEXTGEN_TOOL_TOP_K" == x* ]] && CODEX_TEXTGEN_TOOL_TOP_K="${CALLER_CODEX_TEXTGEN_TOOL_TOP_K#x}"
[[ "$CALLER_CODEX_TEXTGEN_TOOL_MIN_P" == x* ]] && CODEX_TEXTGEN_TOOL_MIN_P="${CALLER_CODEX_TEXTGEN_TOOL_MIN_P#x}"
[[ "$CALLER_CODEX_TEXTGEN_TOOL_REASONING_EFFORT" == x* ]] && CODEX_TEXTGEN_TOOL_REASONING_EFFORT="${CALLER_CODEX_TEXTGEN_TOOL_REASONING_EFFORT#x}"
[[ "$CALLER_CODEX_TEXTGEN_ENABLE_THINKING" == x* ]] && CODEX_TEXTGEN_ENABLE_THINKING="${CALLER_CODEX_TEXTGEN_ENABLE_THINKING#x}"
[[ "$CALLER_CODEX_TEXTGEN_PRESERVE_THINKING" == x* ]] && CODEX_TEXTGEN_PRESERVE_THINKING="${CALLER_CODEX_TEXTGEN_PRESERVE_THINKING#x}"
[[ "$CALLER_CODEX_TEXTGEN_THINKING_MIN_OUTPUT_TOKENS" == x* ]] && CODEX_TEXTGEN_THINKING_MIN_OUTPUT_TOKENS="${CALLER_CODEX_TEXTGEN_THINKING_MIN_OUTPUT_TOKENS#x}"
[[ "$CALLER_CODEX_TEXTGEN_DISABLE_THINKING_FOR_TOOLS" == x* ]] && CODEX_TEXTGEN_DISABLE_THINKING_FOR_TOOLS="${CALLER_CODEX_TEXTGEN_DISABLE_THINKING_FOR_TOOLS#x}"
[[ "$CALLER_CODEX_TEXTGEN_REASONING_DEFAULT_EFFORT" == x* ]] && CODEX_TEXTGEN_REASONING_DEFAULT_EFFORT="${CALLER_CODEX_TEXTGEN_REASONING_DEFAULT_EFFORT#x}"
[[ "$CALLER_CODEX_TEXTGEN_REASONING_BUDGET_LOW" == x* ]] && CODEX_TEXTGEN_REASONING_BUDGET_LOW="${CALLER_CODEX_TEXTGEN_REASONING_BUDGET_LOW#x}"
[[ "$CALLER_CODEX_TEXTGEN_REASONING_BUDGET_MEDIUM" == x* ]] && CODEX_TEXTGEN_REASONING_BUDGET_MEDIUM="${CALLER_CODEX_TEXTGEN_REASONING_BUDGET_MEDIUM#x}"
[[ "$CALLER_CODEX_TEXTGEN_REASONING_BUDGET_XHIGH" == x* ]] && CODEX_TEXTGEN_REASONING_BUDGET_XHIGH="${CALLER_CODEX_TEXTGEN_REASONING_BUDGET_XHIGH#x}"
[[ "$CALLER_CODEX_TEXTGEN_REASONING_OUTPUT_RESERVE_TOKENS" == x* ]] && CODEX_TEXTGEN_REASONING_OUTPUT_RESERVE_TOKENS="${CALLER_CODEX_TEXTGEN_REASONING_OUTPUT_RESERVE_TOKENS#x}"
[[ "$CALLER_CODEX_TEXTGEN_NATIVE_TOOLS" == x* ]] && CODEX_TEXTGEN_NATIVE_TOOLS="${CALLER_CODEX_TEXTGEN_NATIVE_TOOLS#x}"
[[ "$CALLER_CODEX_TEXTGEN_SYSTEM_PROMPT_FILE" == x* ]] && CODEX_TEXTGEN_SYSTEM_PROMPT_FILE="${CALLER_CODEX_TEXTGEN_SYSTEM_PROMPT_FILE#x}"
[[ "$CALLER_CODEX_TEXTGEN_LOG_PATH" == x* ]] && CODEX_TEXTGEN_LOG_PATH="${CALLER_CODEX_TEXTGEN_LOG_PATH#x}"
[[ "$CALLER_LOCAL_QWEN_GUARD_PROFILE" == x* ]] && LOCAL_QWEN_GUARD_PROFILE="${CALLER_LOCAL_QWEN_GUARD_PROFILE#x}"
[[ "$CALLER_LOCAL_QWEN_CODEX_MAX_TOOL_CALLS" == x* ]] && LOCAL_QWEN_CODEX_MAX_TOOL_CALLS="${CALLER_LOCAL_QWEN_CODEX_MAX_TOOL_CALLS#x}"
[[ "$CALLER_LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS" == x* ]] && LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS="${CALLER_LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS#x}"

BRIDGE="$ROOT/scripts/qwendex_responses_bridge.py"
HOST="${CODEX_TEXTGEN_BRIDGE_HOST:-127.0.0.1}"
PORT="${CODEX_TEXTGEN_BRIDGE_PORT:-1234}"
TARGET="${CODEX_TEXTGEN_TARGET_BASE:-${LITELLM_BASE:-http://127.0.0.1:4000}}"
LOCAL_MODEL="${LOCAL_QWEN_MODEL:-qwen-local}"
SYSTEM_PROMPT_FILE="${CODEX_TEXTGEN_SYSTEM_PROMPT_FILE:-}"
MAX_OUTPUT_TOKENS="${CODEX_TEXTGEN_MAX_OUTPUT_TOKENS:-2048}"
CONTEXT_LIMIT_TOKENS="${CODEX_TEXTGEN_CONTEXT_LIMIT_TOKENS:-${TEXTGEN_CTX_SIZE:-98304}}"
MAX_FORWARD_BODY_BYTES="${CODEX_TEXTGEN_MAX_FORWARD_BODY_BYTES:-900000}"
TOOL_TEMPERATURE="${CODEX_TEXTGEN_TOOL_TEMPERATURE:-0.15}"
TOOL_TOP_P="${CODEX_TEXTGEN_TOOL_TOP_P:-}"
TOOL_TOP_K="${CODEX_TEXTGEN_TOOL_TOP_K:-}"
TOOL_MIN_P="${CODEX_TEXTGEN_TOOL_MIN_P:-}"
TOOL_REASONING_EFFORT="${CODEX_TEXTGEN_TOOL_REASONING_EFFORT:-}"
ENABLE_THINKING="${CODEX_TEXTGEN_ENABLE_THINKING:-false}"
PRESERVE_THINKING="${CODEX_TEXTGEN_PRESERVE_THINKING:-false}"
THINKING_MIN_OUTPUT_TOKENS="${CODEX_TEXTGEN_THINKING_MIN_OUTPUT_TOKENS:-0}"
DISABLE_THINKING_FOR_TOOLS="${CODEX_TEXTGEN_DISABLE_THINKING_FOR_TOOLS:-false}"
REASONING_DEFAULT_EFFORT="${CODEX_TEXTGEN_REASONING_DEFAULT_EFFORT:-medium}"
REASONING_BUDGET_LOW="${CODEX_TEXTGEN_REASONING_BUDGET_LOW:-1024}"
REASONING_BUDGET_MEDIUM="${CODEX_TEXTGEN_REASONING_BUDGET_MEDIUM:-2048}"
REASONING_BUDGET_XHIGH="${CODEX_TEXTGEN_REASONING_BUDGET_XHIGH:-4096}"
REASONING_OUTPUT_RESERVE_TOKENS="${CODEX_TEXTGEN_REASONING_OUTPUT_RESERVE_TOKENS:-1024}"
NATIVE_TOOLS="${CODEX_TEXTGEN_NATIVE_TOOLS:-false}"
UPSTREAM_TIMEOUT_SECONDS="${CODEX_TEXTGEN_UPSTREAM_TIMEOUT_SECONDS:-600}"
LOG_PATH="${CODEX_TEXTGEN_LOG_PATH:-${XDG_STATE_HOME:-$HOME/.local/state}/qwendex/local_qwen_bridge/responses_bridge.jsonl}"
LOCAL_QWEN_GUARD_PROFILE="${LOCAL_QWEN_GUARD_PROFILE:-balanced}"
LOCAL_QWEN_CODEX_MAX_TOOL_CALLS="${LOCAL_QWEN_CODEX_MAX_TOOL_CALLS:--1}"
LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS="${LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS:--1}"

validate_budget_value() {
  local name="$1"
  local value="$2"
  local allow_zero="$3"
  local allowed="-1 or a positive integer"
  if [[ "$allow_zero" == "1" ]]; then
    allowed="-1, 0, or a positive integer"
  fi
  if [[ -z "$value" || "$value" == "-1" ]]; then
    return 0
  fi
  if [[ "$allow_zero" == "1" && "$value" == "0" ]]; then
    return 0
  fi
  if [[ ! "$value" =~ ^[0-9]+$ ]]; then
    echo "$name must be $allowed; got: $value" >&2
    exit 2
  fi
  if [[ "$value" == "0" ]]; then
    echo "$name must be $allowed; got: 0" >&2
    exit 2
  fi
}

validate_runtime_guard_config() {
  case "$LOCAL_QWEN_GUARD_PROFILE" in
    balanced|max_safety) ;;
    *)
      echo "LOCAL_QWEN_GUARD_PROFILE must be balanced or max_safety; got: $LOCAL_QWEN_GUARD_PROFILE" >&2
      exit 2
      ;;
  esac
  validate_budget_value LOCAL_QWEN_CODEX_MAX_TOOL_CALLS "$LOCAL_QWEN_CODEX_MAX_TOOL_CALLS" 1
  validate_budget_value LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS "$LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS" 0
}

validate_runtime_guard_config

validate_positive_integer() {
  local name="$1"
  local value="$2"
  if [[ ! "$value" =~ ^[0-9]+$ || "$value" == "0" ]]; then
    echo "$name must be a positive integer; got: $value" >&2
    exit 2
  fi
}

if [[ ! "$THINKING_MIN_OUTPUT_TOKENS" =~ ^[0-9]+$ ]]; then
  echo "CODEX_TEXTGEN_THINKING_MIN_OUTPUT_TOKENS must be a non-negative integer; got: $THINKING_MIN_OUTPUT_TOKENS" >&2
  exit 2
fi
case "$DISABLE_THINKING_FOR_TOOLS" in
  true|false) ;;
  *)
    echo "CODEX_TEXTGEN_DISABLE_THINKING_FOR_TOOLS must be true or false; got: $DISABLE_THINKING_FOR_TOOLS" >&2
    exit 2
    ;;
esac
case "$REASONING_DEFAULT_EFFORT" in
  low|medium|xhigh) ;;
  *)
    echo "CODEX_TEXTGEN_REASONING_DEFAULT_EFFORT must be low, medium, or xhigh; got: $REASONING_DEFAULT_EFFORT" >&2
    exit 2
    ;;
esac
validate_positive_integer CODEX_TEXTGEN_REASONING_BUDGET_LOW "$REASONING_BUDGET_LOW"
validate_positive_integer CODEX_TEXTGEN_REASONING_BUDGET_MEDIUM "$REASONING_BUDGET_MEDIUM"
validate_positive_integer CODEX_TEXTGEN_REASONING_BUDGET_XHIGH "$REASONING_BUDGET_XHIGH"
if [[ ! "$REASONING_OUTPUT_RESERVE_TOKENS" =~ ^[0-9]+$ ]]; then
  echo "CODEX_TEXTGEN_REASONING_OUTPUT_RESERVE_TOKENS must be a non-negative integer; got: $REASONING_OUTPUT_RESERVE_TOKENS" >&2
  exit 2
fi
case "$NATIVE_TOOLS" in
  true|false) ;;
  *)
    echo "CODEX_TEXTGEN_NATIVE_TOOLS must be true or false; got: $NATIVE_TOOLS" >&2
    exit 2
    ;;
esac

if [[ ! -f "$BRIDGE" ]]; then
  echo "Missing responses bridge: $BRIDGE" >&2
  exit 1
fi

SYSTEM_PROMPT_ARGS=()
if [[ -n "$SYSTEM_PROMPT_FILE" ]]; then
  if [[ ! -f "$SYSTEM_PROMPT_FILE" ]]; then
    echo "Missing system prompt: $SYSTEM_PROMPT_FILE" >&2
    exit 1
  fi
  SYSTEM_PROMPT_ARGS=(--system-prompt-file "$SYSTEM_PROMPT_FILE")
fi

SAMPLER_ARGS=()
[[ -n "$TOOL_TOP_P" ]] && SAMPLER_ARGS+=(--tool-top-p "$TOOL_TOP_P")
[[ -n "$TOOL_TOP_K" ]] && SAMPLER_ARGS+=(--tool-top-k "$TOOL_TOP_K")
[[ -n "$TOOL_MIN_P" ]] && SAMPLER_ARGS+=(--tool-min-p "$TOOL_MIN_P")
[[ -n "$TOOL_REASONING_EFFORT" ]] && SAMPLER_ARGS+=(--tool-reasoning-effort "$TOOL_REASONING_EFFORT")
NATIVE_TOOL_ARGS=()
[[ "$NATIVE_TOOLS" == "true" ]] && NATIVE_TOOL_ARGS+=(--native-tools)

if ! curl -fsS --max-time 3 "$TARGET/v1/models" >/dev/null; then
  echo "Target is not healthy at $TARGET/v1/models" >&2
  echo "Start TextGen and LiteLLM first." >&2
  exit 1
fi

echo "Starting Codex responses bridge on http://$HOST:$PORT -> $TARGET"
exec python3 "$BRIDGE" \
  --listen-host "$HOST" \
  --listen-port "$PORT" \
  --target-base "$TARGET" \
  --local-model "$LOCAL_MODEL" \
  "${SYSTEM_PROMPT_ARGS[@]}" \
  --max-output-tokens "$MAX_OUTPUT_TOKENS" \
  --context-limit-tokens "$CONTEXT_LIMIT_TOKENS" \
  --max-forward-body-bytes "$MAX_FORWARD_BODY_BYTES" \
  --log-path "$LOG_PATH" \
  --tool-temperature "$TOOL_TEMPERATURE" \
  --enable-thinking "$ENABLE_THINKING" \
  --preserve-thinking "$PRESERVE_THINKING" \
  --thinking-min-output-tokens "$THINKING_MIN_OUTPUT_TOKENS" \
  --disable-thinking-for-tools "$DISABLE_THINKING_FOR_TOOLS" \
  --reasoning-default-effort "$REASONING_DEFAULT_EFFORT" \
  --reasoning-budget-low "$REASONING_BUDGET_LOW" \
  --reasoning-budget-medium "$REASONING_BUDGET_MEDIUM" \
  --reasoning-budget-xhigh "$REASONING_BUDGET_XHIGH" \
  --reasoning-output-reserve-tokens "$REASONING_OUTPUT_RESERVE_TOKENS" \
  "${NATIVE_TOOL_ARGS[@]}" \
  "${SAMPLER_ARGS[@]}" \
  --upstream-timeout-seconds "$UPSTREAM_TIMEOUT_SECONDS"
