#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/config/local_llm_stack/local_harness.env"
CALLER_CODEX_TEXTGEN_TARGET_BASE="${CODEX_TEXTGEN_TARGET_BASE+x}${CODEX_TEXTGEN_TARGET_BASE-}"
CALLER_CODEX_TEXTGEN_CONTEXT_LIMIT_TOKENS="${CODEX_TEXTGEN_CONTEXT_LIMIT_TOKENS+x}${CODEX_TEXTGEN_CONTEXT_LIMIT_TOKENS-}"
CALLER_CODEX_TEXTGEN_MAX_OUTPUT_TOKENS="${CODEX_TEXTGEN_MAX_OUTPUT_TOKENS+x}${CODEX_TEXTGEN_MAX_OUTPUT_TOKENS-}"
CALLER_CODEX_TEXTGEN_TOOL_TEMPERATURE="${CODEX_TEXTGEN_TOOL_TEMPERATURE+x}${CODEX_TEXTGEN_TOOL_TEMPERATURE-}"
CALLER_CODEX_TEXTGEN_TOOL_TOP_P="${CODEX_TEXTGEN_TOOL_TOP_P+x}${CODEX_TEXTGEN_TOOL_TOP_P-}"
CALLER_CODEX_TEXTGEN_TOOL_TOP_K="${CODEX_TEXTGEN_TOOL_TOP_K+x}${CODEX_TEXTGEN_TOOL_TOP_K-}"
CALLER_CODEX_TEXTGEN_TOOL_MIN_P="${CODEX_TEXTGEN_TOOL_MIN_P+x}${CODEX_TEXTGEN_TOOL_MIN_P-}"
CALLER_CODEX_TEXTGEN_TOOL_REASONING_EFFORT="${CODEX_TEXTGEN_TOOL_REASONING_EFFORT+x}${CODEX_TEXTGEN_TOOL_REASONING_EFFORT-}"
CALLER_CODEX_TEXTGEN_ENABLE_THINKING="${CODEX_TEXTGEN_ENABLE_THINKING+x}${CODEX_TEXTGEN_ENABLE_THINKING-}"
CALLER_CODEX_TEXTGEN_PRESERVE_THINKING="${CODEX_TEXTGEN_PRESERVE_THINKING+x}${CODEX_TEXTGEN_PRESERVE_THINKING-}"
CALLER_CODEX_TEXTGEN_SYSTEM_PROMPT_FILE="${CODEX_TEXTGEN_SYSTEM_PROMPT_FILE+x}${CODEX_TEXTGEN_SYSTEM_PROMPT_FILE-}"
CALLER_CODEX_TEXTGEN_LOG_PATH="${CODEX_TEXTGEN_LOG_PATH+x}${CODEX_TEXTGEN_LOG_PATH-}"
CALLER_LOCAL_QWEN_GUARD_PROFILE="${LOCAL_QWEN_GUARD_PROFILE+x}${LOCAL_QWEN_GUARD_PROFILE-}"
CALLER_LOCAL_QWEN_CODEX_MAX_TOOL_CALLS="${LOCAL_QWEN_CODEX_MAX_TOOL_CALLS+x}${LOCAL_QWEN_CODEX_MAX_TOOL_CALLS-}"
CALLER_LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS="${LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS+x}${LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS-}"
if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi
[[ "$CALLER_CODEX_TEXTGEN_TARGET_BASE" == x* ]] && CODEX_TEXTGEN_TARGET_BASE="${CALLER_CODEX_TEXTGEN_TARGET_BASE#x}"
[[ "$CALLER_CODEX_TEXTGEN_CONTEXT_LIMIT_TOKENS" == x* ]] && CODEX_TEXTGEN_CONTEXT_LIMIT_TOKENS="${CALLER_CODEX_TEXTGEN_CONTEXT_LIMIT_TOKENS#x}"
[[ "$CALLER_CODEX_TEXTGEN_MAX_OUTPUT_TOKENS" == x* ]] && CODEX_TEXTGEN_MAX_OUTPUT_TOKENS="${CALLER_CODEX_TEXTGEN_MAX_OUTPUT_TOKENS#x}"
[[ "$CALLER_CODEX_TEXTGEN_TOOL_TEMPERATURE" == x* ]] && CODEX_TEXTGEN_TOOL_TEMPERATURE="${CALLER_CODEX_TEXTGEN_TOOL_TEMPERATURE#x}"
[[ "$CALLER_CODEX_TEXTGEN_TOOL_TOP_P" == x* ]] && CODEX_TEXTGEN_TOOL_TOP_P="${CALLER_CODEX_TEXTGEN_TOOL_TOP_P#x}"
[[ "$CALLER_CODEX_TEXTGEN_TOOL_TOP_K" == x* ]] && CODEX_TEXTGEN_TOOL_TOP_K="${CALLER_CODEX_TEXTGEN_TOOL_TOP_K#x}"
[[ "$CALLER_CODEX_TEXTGEN_TOOL_MIN_P" == x* ]] && CODEX_TEXTGEN_TOOL_MIN_P="${CALLER_CODEX_TEXTGEN_TOOL_MIN_P#x}"
[[ "$CALLER_CODEX_TEXTGEN_TOOL_REASONING_EFFORT" == x* ]] && CODEX_TEXTGEN_TOOL_REASONING_EFFORT="${CALLER_CODEX_TEXTGEN_TOOL_REASONING_EFFORT#x}"
[[ "$CALLER_CODEX_TEXTGEN_ENABLE_THINKING" == x* ]] && CODEX_TEXTGEN_ENABLE_THINKING="${CALLER_CODEX_TEXTGEN_ENABLE_THINKING#x}"
[[ "$CALLER_CODEX_TEXTGEN_PRESERVE_THINKING" == x* ]] && CODEX_TEXTGEN_PRESERVE_THINKING="${CALLER_CODEX_TEXTGEN_PRESERVE_THINKING#x}"
[[ "$CALLER_CODEX_TEXTGEN_SYSTEM_PROMPT_FILE" == x* ]] && CODEX_TEXTGEN_SYSTEM_PROMPT_FILE="${CALLER_CODEX_TEXTGEN_SYSTEM_PROMPT_FILE#x}"
[[ "$CALLER_CODEX_TEXTGEN_LOG_PATH" == x* ]] && CODEX_TEXTGEN_LOG_PATH="${CALLER_CODEX_TEXTGEN_LOG_PATH#x}"
[[ "$CALLER_LOCAL_QWEN_GUARD_PROFILE" == x* ]] && LOCAL_QWEN_GUARD_PROFILE="${CALLER_LOCAL_QWEN_GUARD_PROFILE#x}"
[[ "$CALLER_LOCAL_QWEN_CODEX_MAX_TOOL_CALLS" == x* ]] && LOCAL_QWEN_CODEX_MAX_TOOL_CALLS="${CALLER_LOCAL_QWEN_CODEX_MAX_TOOL_CALLS#x}"
[[ "$CALLER_LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS" == x* ]] && LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS="${CALLER_LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS#x}"

BRIDGE="$ROOT/scripts/qwendex_responses_bridge.py"
HOST="${CODEX_TEXTGEN_BRIDGE_HOST:-127.0.0.1}"
PORT="${CODEX_TEXTGEN_BRIDGE_PORT:-1234}"
TARGET="${CODEX_TEXTGEN_TARGET_BASE:-${LITELLM_BASE:-http://127.0.0.1:4000}}"
SYSTEM_PROMPT_FILE="${CODEX_TEXTGEN_SYSTEM_PROMPT_FILE:-}"
MAX_OUTPUT_TOKENS="${CODEX_TEXTGEN_MAX_OUTPUT_TOKENS:-2048}"
CONTEXT_LIMIT_TOKENS="${CODEX_TEXTGEN_CONTEXT_LIMIT_TOKENS:-${TEXTGEN_CTX_SIZE:-98304}}"
MAX_FORWARD_BODY_BYTES="${CODEX_TEXTGEN_MAX_FORWARD_BODY_BYTES:-900000}"
TOOL_TEMPERATURE="${CODEX_TEXTGEN_TOOL_TEMPERATURE:-0.15}"
TOOL_TOP_P="${CODEX_TEXTGEN_TOOL_TOP_P:-}"
TOOL_TOP_K="${CODEX_TEXTGEN_TOOL_TOP_K:-}"
TOOL_MIN_P="${CODEX_TEXTGEN_TOOL_MIN_P:-}"
TOOL_REASONING_EFFORT="${CODEX_TEXTGEN_TOOL_REASONING_EFFORT:-}"
ENABLE_THINKING="${CODEX_TEXTGEN_ENABLE_THINKING:-false}"
PRESERVE_THINKING="${CODEX_TEXTGEN_PRESERVE_THINKING:-false}"
UPSTREAM_TIMEOUT_SECONDS="${CODEX_TEXTGEN_UPSTREAM_TIMEOUT_SECONDS:-600}"
LOG_PATH="${CODEX_TEXTGEN_LOG_PATH:-${XDG_STATE_HOME:-$HOME/.local/state}/qwendex/local_qwen_bridge/responses_bridge.jsonl}"
LOCAL_QWEN_GUARD_PROFILE="${LOCAL_QWEN_GUARD_PROFILE:-balanced}"
LOCAL_QWEN_CODEX_MAX_TOOL_CALLS="${LOCAL_QWEN_CODEX_MAX_TOOL_CALLS:--1}"
LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS="${LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS:--1}"

validate_budget_value() {
  local name="$1"
  local value="$2"
  local allow_zero="$3"
  local allowed="-1 or a positive integer"
  if [[ "$allow_zero" == "1" ]]; then
    allowed="-1, 0, or a positive integer"
  fi
  if [[ -z "$value" || "$value" == "-1" ]]; then
    return 0
  fi
  if [[ "$allow_zero" == "1" && "$value" == "0" ]]; then
    return 0
  fi
  if [[ ! "$value" =~ ^[0-9]+$ ]]; then
    echo "$name must be $allowed; got: $value" >&2
    exit 2
  fi
  if [[ "$value" == "0" ]]; then
    echo "$name must be $allowed; got: 0" >&2
    exit 2
  fi
}

validate_runtime_guard_config() {
  case "$LOCAL_QWEN_GUARD_PROFILE" in
    balanced|max_safety) ;;
    *)
      echo "LOCAL_QWEN_GUARD_PROFILE must be balanced or max_safety; got: $LOCAL_QWEN_GUARD_PROFILE" >&2
      exit 2
      ;;
  esac
  validate_budget_value LOCAL_QWEN_CODEX_MAX_TOOL_CALLS "$LOCAL_QWEN_CODEX_MAX_TOOL_CALLS" 1
  validate_budget_value LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS "$LOCAL_QWEN_CODEX_MAX_WALL_TIME_SECONDS" 0
}

validate_runtime_guard_config

if [[ ! -f "$BRIDGE" ]]; then
  echo "Missing responses bridge: $BRIDGE" >&2
  exit 1
fi

SYSTEM_PROMPT_ARGS=()
if [[ -n "$SYSTEM_PROMPT_FILE" ]]; then
  if [[ ! -f "$SYSTEM_PROMPT_FILE" ]]; then
    echo "Missing system prompt: $SYSTEM_PROMPT_FILE" >&2
    exit 1
  fi
  SYSTEM_PROMPT_ARGS=(--system-prompt-file "$SYSTEM_PROMPT_FILE")
fi

SAMPLER_ARGS=()
[[ -n "$TOOL_TOP_P" ]] && SAMPLER_ARGS+=(--tool-top-p "$TOOL_TOP_P")
[[ -n "$TOOL_TOP_K" ]] && SAMPLER_ARGS+=(--tool-top-k "$TOOL_TOP_K")
[[ -n "$TOOL_MIN_P" ]] && SAMPLER_ARGS+=(--tool-min-p "$TOOL_MIN_P")
[[ -n "$TOOL_REASONING_EFFORT" ]] && SAMPLER_ARGS+=(--tool-reasoning-effort "$TOOL_REASONING_EFFORT")

if ! curl -fsS --max-time 3 "$TARGET/v1/models" >/dev/null; then
  echo "Target is not healthy at $TARGET/v1/models" >&2
  echo "Start TextGen and LiteLLM first." >&2
  exit 1
fi

echo "Starting Codex responses bridge on http://$HOST:$PORT -> $TARGET"
exec python3 "$BRIDGE" \
  --listen-host "$HOST" \
  --listen-port "$PORT" \
  --target-base "$TARGET" \
  "${SYSTEM_PROMPT_ARGS[@]}" \
  --max-output-tokens "$MAX_OUTPUT_TOKENS" \
  --context-limit-tokens "$CONTEXT_LIMIT_TOKENS" \
  --max-forward-body-bytes "$MAX_FORWARD_BODY_BYTES" \
  --log-path "$LOG_PATH" \
  --tool-temperature "$TOOL_TEMPERATURE" \
  --enable-thinking "$ENABLE_THINKING" \
  --preserve-thinking "$PRESERVE_THINKING" \
  "${SAMPLER_ARGS[@]}" \
  --upstream-timeout-seconds "$UPSTREAM_TIMEOUT_SECONDS"
